### ISSUE TITLE
serial has reached the maximum number of activations.

### ISSUE THREAD

**Issue by h53** [game-ci/unity3d-ci-example#21]
I get this error when I upload activation file to license.unity3d.com/manual

**Comment by GabLeRoux** [comment]
Your title says it all, if you're using a serial number, make sure you free up the seats so you can activate it again.  
https://support.unity.com/hc/en-us/articles/205056069-How-do-I-return-the-activations-on-my-Pro-Plus-Enterprise-license-

**Comment by kirsting** [comment]
same when I try to activate personal license. do i need to run this on self-hosted runners?
