### ISSUE TITLE
No example for GitHub workflows?

### ISSUE THREAD

**Issue by hakanai** [game-ci/unity3d-ci-example#22]
I am looking for an example of a GitHub workflow using GameCI and thought it would be here, but it was not.

**Comment by GabLeRoux** [comment]
Thanks for pointing this out. Indeed, this is actually a mirror of https://gitlab.com/gableroux/unity3d-gitlab-ci-example and I realize its name differs so I'll rename it to reduce confusion.

For a Github Actions example, you can refer to https://github.com/game-ci/unity-actions-example or https://github.com/game-ci/unity-actions

👍
